// Bilingual copy — EN keeps our voice; AR is warm professional MSA.
// MarQ stays Latin in Arabic per the brand book.

export const CONTENT = {
  en: {
    nav: { home: 'Home', services: 'Services', work: 'Work', about: 'About', contact: 'Contact', studio: 'Studio', cta: "Let's Talk" },
    hero: {
      tagA: 'Branding Studio',
      tagB: 'Tripoli, Libya',
      head: ['Make Your', 'Mark'],
      lead: 'A Libyan branding studio.',
      sub: 'MarQ is a Libyan branding studio that transforms ambitious ideas into identities people recognise, trust, and remember.',
      locLabel: 'Base of Operations',
      locValue: 'Tripoli, Libya',
      coords: '32.8872° N, 13.1913° E',
      statNum: '120+',
      statLabel: 'Brands Shaped',
      scroll: 'Scroll',
      explore: 'Explore',
    },
    services: {
      index: '01',
      kicker: 'Our Services',
      head: ['What', 'We Do'],
      intro: 'From strategy to production, we deliver one connected brand system — not a stack of unrelated projects.',
      items: [
        { num: '01', title: 'Brand Strategy', desc: 'Positioning, architecture, naming, audience insight, and brand voice.' },
        { num: '02', title: 'Identity & Design', desc: 'Logos, visual systems, typography, guidelines, and art direction.' },
        { num: '03', title: 'Digital', desc: 'Websites, UI/UX, social systems, motion, and digital experiences.' },
        { num: '04', title: 'Communication', desc: 'Campaigns, content strategy, social management, and internal comms.' },
        { num: '05', title: 'Production', desc: 'Print, packaging, photography, video, and event design.' },
        { num: '06', title: 'Brand Care', desc: 'Ongoing design partnership, templates, and asset systems.' },
      ],
    },
    work: {
      index: '03',
      kicker: 'Selected Work',
      head: ['Selected', 'Works'],
      viewAll: 'View All Projects',
      items: [
        { name: 'Tikkan F&B', cat: 'Branding & Identity', year: '2026' },
        { name: 'Yalla Logistics', cat: 'Strategy & Digital', year: '2025' },
        { name: 'Noor Clinic', cat: 'Identity & Space', year: '2025' },
        { name: 'Falcon Fintech', cat: 'Brand & Product', year: '2024' },
      ],
    },
    footer: {
      index: '04',
      kicker: 'Start a Conversation',
      head: ['Leave a', 'Mark'],
      blurb: 'Ready to build a brand worth remembering? We take on bold projects across Libya and beyond.',
      tagline: 'A Libyan branding studio building identities that last.',
      linksLabel: 'Navigate',
      contactLabel: 'Contact',
      followLabel: 'Follow',
      email: 'hello@marq.studio',
      phone: '+218 21 000 0000',
      copyright: '© 2025 MarQ — Tripoli, Libya.',
      socials: ['Instagram', 'LinkedIn', 'Behance'],
    },
    why: {
      kicker: 'Our Belief',
      head: ['We build', 'recognition'],
      body: "Most companies chase attention. But a brand isn't a logo or a palette — it's the mark you leave in someone's memory. That's the only thing worth designing for.",
    },
    process: {
      index: '02',
      kicker: 'The Process',
      head: ['How', 'We Work'],
      intro: 'A clear path from the first conversation to launch — and well beyond it.',
      steps: [
        { num: '01', title: 'Discover', desc: 'We learn your world, your audience, and your ambition.' },
        { num: '02', title: 'Define', desc: 'Strategy, positioning, and the core idea everything hangs on.' },
        { num: '03', title: 'Design', desc: 'Identity, system, and every touchpoint — crafted in detail.' },
        { num: '04', title: 'Deliver', desc: 'Rollout across digital, print, and space — then we stay on as your brand partner.' },
      ],
    },
    finalCta: {
      kicker: 'Start a Project',
      head: ['Ready to make', 'your mark?'],
      sub: "Let's build a brand worth remembering.",
      button: 'Start a Conversation',
    },
    about: {
      kicker: 'About the Studio',
      head: ['Who', 'We Are'],
      lead: 'MarQ is a Libyan branding studio building identities that last.',
      story: [
        'We started MarQ with one conviction: a brand is the most valuable thing a company owns — and the most often neglected. From Tripoli, we partner with ambitious organisations across Libya and the region to build brands with clarity, craft, and staying power.',
        'We work as one connected team across strategy, design, and digital — so every touchpoint tells the same story. No hand-offs, no disconnects. One brand, built to be remembered.',
      ],
      valuesKicker: 'What We Believe',
      values: [
        { title: 'Clarity over noise', desc: 'Strong brands say one thing well. We cut to the core idea and build everything around it.' },
        { title: 'Craft in every detail', desc: 'From the logo to the last caption, quality is felt — not described.' },
        { title: 'Partnership, not projects', desc: 'We work like your in-house brand team, invested in the long game.' },
        { title: 'Built to last', desc: 'We design identities that still feel right years from now, not just on launch day.' },
      ],
      cta: 'Work with us',
    },
    servicesPage: {
      kicker: 'Capabilities',
      head: ['What', 'We Offer'],
      intro: 'Six connected disciplines, one brand system. Engage us for a single need or the full journey.',
      deliverablesLabel: 'What you get',
      items: [
        { deliverables: ['Brand audit & positioning', 'Naming & messaging', 'Audience & market insight', 'Tone of voice'] },
        { deliverables: ['Logo & wordmark', 'Visual identity system', 'Typography & colour', 'Brand guidelines'] },
        { deliverables: ['Website design & build', 'UI / UX', 'Social media systems', 'Motion & interaction'] },
        { deliverables: ['Campaign concepts', 'Content strategy', 'Social management', 'Internal comms'] },
        { deliverables: ['Print & packaging', 'Photography & video', 'Event & space design', 'Production management'] },
        { deliverables: ['Ongoing design partnership', 'Templates & toolkits', 'Asset libraries', 'Brand governance'] },
      ],
      cta: "Let's talk",
    },
    contact: {
      kicker: 'Get in Touch',
      head: ['Say', 'Hello'],
      intro: 'Tell us about your brand and what you want to build. We reply within two business days.',
      form: {
        name: 'Your name',
        email: 'Email',
        company: 'Company',
        budget: 'Budget',
        budgetOptions: ['Not sure yet', 'Under $5k', '$5k – $15k', '$15k – $50k', '$50k+'],
        message: 'Tell us about your project',
        submit: 'Send enquiry',
        sending: 'Sending…',
        success: "Thanks — your message is on its way. We'll be in touch within two business days.",
        required: 'Please fill in the required fields.',
      },
      detailsKicker: 'Direct',
      emailLabel: 'Email',
      phoneLabel: 'Phone',
      locationLabel: 'Studio',
      followLabel: 'Follow',
    },
  },

  ar: {
    nav: { home: 'الرئيسية', services: 'خدماتنا', work: 'أعمالنا', about: 'من نحن', contact: 'تواصل', studio: 'الاستوديو', cta: 'لنتحدّث' },
    hero: {
      tagA: 'استوديو علامات تجارية',
      tagB: 'طرابلس',
      head: ['اترك', 'أثرك'],
      lead: 'استوديو ليبي للعلامات التجارية.',
      sub: 'MarQ استوديو ليبي للعلامات التجارية — نحوّل الأفكار الطموحة إلى هويات يتعرّف عليها الناس، ويثقون بها، ويتذكّرونها.',
      locLabel: 'مقرّ العمل',
      locValue: 'طرابلس، ليبيا',
      coords: '32.8872° N, 13.1913° E',
      statNum: '120+',
      statLabel: 'علامة صُمّمت',
      scroll: 'مرّر',
      explore: 'استكشف',
    },
    services: {
      index: '01',
      kicker: 'خدماتنا',
      head: ['ما', 'نقدّمه'],
      intro: 'من الاستراتيجية إلى الإنتاج، نُسلّم نظاماً واحداً مترابطاً — لا مشاريع منفصلة.',
      items: [
        { num: '01', title: 'استراتيجية العلامة', desc: 'التموضع، هيكلة العلامة، التسمية، دراسة الجمهور، وصوت العلامة.' },
        { num: '02', title: 'الهوية والتصميم', desc: 'الشعارات، الأنظمة البصرية، الخطوط، الإرشادات، والإدارة الفنية.' },
        { num: '03', title: 'الرقمي', desc: 'المواقع، تجربة المستخدم، أنظمة التواصل الاجتماعي، والتجارب الرقمية.' },
        { num: '04', title: 'التواصل', desc: 'الحملات، استراتيجية المحتوى، إدارة التواصل الاجتماعي، والتواصل الداخلي.' },
        { num: '05', title: 'الإنتاج', desc: 'الطباعة، التغليف، التصوير، الفيديو، وتصميم الفعاليات.' },
        { num: '06', title: 'رعاية العلامة', desc: 'شراكة تصميم مستمرة، قوالب، وأنظمة أصول.' },
      ],
    },
    work: {
      index: '03',
      kicker: 'أعمال مختارة',
      head: ['أعمال', 'مختارة'],
      viewAll: 'عرض كل الأعمال',
      items: [
        { name: 'تِكان للأطعمة', cat: 'علامة وهوية', year: '2026' },
        { name: 'يلا لوجستيك', cat: 'استراتيجية ورقمي', year: '2025' },
        { name: 'عيادة نور', cat: 'هوية ومكان', year: '2025' },
        { name: 'فالكون فينتك', cat: 'علامة ومنتج', year: '2024' },
      ],
    },
    footer: {
      index: '04',
      kicker: 'ابدأ محادثة',
      head: ['اترك', 'أثراً'],
      blurb: 'مستعدّ لبناء علامة تُذكر؟ نتولّى المشاريع الجريئة في ليبيا وخارجها.',
      tagline: 'استوديو ليبي للعلامات التجارية يبني هويات تبقى.',
      linksLabel: 'تصفّح',
      contactLabel: 'تواصل',
      followLabel: 'تابعنا',
      email: 'hello@marq.studio',
      phone: '+218 21 000 0000',
      copyright: '© 2025 MarQ — طرابلس، ليبيا.',
      socials: ['Instagram', 'LinkedIn', 'Behance'],
    },
    why: {
      kicker: 'فلسفتنا',
      head: ['نصنع', 'التميّز'],
      body: 'معظم الشركات تسعى وراء الانتباه. لكن العلامة ليست شعاراً أو مجموعة ألوان، بل هي الأثر الذي تتركه في ذاكرة الناس. وذلك وحده ما يستحقّ التصميم.',
    },
    process: {
      index: '02',
      kicker: 'منهجيتنا',
      head: ['كيف', 'نعمل'],
      intro: 'مسارٌ واضح من أول حديث إلى الإطلاق وما بعده.',
      steps: [
        { num: '01', title: 'اكتشاف', desc: 'نتعرّف على عالمك وجمهورك وطموحك.' },
        { num: '02', title: 'تحديد', desc: 'الاستراتيجية والتموضع والفكرة الجوهرية التي يقوم عليها كل شيء.' },
        { num: '03', title: 'تصميم', desc: 'الهوية والنظام وكل نقطة تواصل، مصوغة بعناية.' },
        { num: '04', title: 'تسليم', desc: 'الإطلاق عبر الرقمي والمطبوع والمكان، ثم نبقى شريكك في العلامة.' },
      ],
    },
    finalCta: {
      kicker: 'ابدأ مشروعاً',
      head: ['مستعدّ لترك', 'أثرك؟'],
      sub: 'لنبنِ علامةً تُذكر.',
      button: 'ابدأ محادثة',
    },
    about: {
      kicker: 'عن الاستوديو',
      head: ['من', 'نحن'],
      lead: 'MarQ استوديو ليبي للعلامات التجارية يبني هويات تبقى.',
      story: [
        'بدأنا MarQ بقناعة واحدة: العلامة التجارية أثمن ما تملكه أي شركة، وأكثر ما يُهمَل. من طرابلس، نعمل مع المؤسسات الطموحة في ليبيا والمنطقة لبناء علامات تتّسم بالوضوح والإتقان والقدرة على البقاء.',
        'نعمل كفريق واحد متكامل عبر الاستراتيجية والتصميم والرقمي، لتروي كل نقطة تواصل القصة نفسها. دون انقطاع ودون تشتّت. علامة واحدة، تُبنى لتُذكر.',
      ],
      valuesKicker: 'ما نؤمن به',
      values: [
        { title: 'الوضوح قبل الضجيج', desc: 'العلامات القوية تقول شيئاً واحداً بإتقان. نصل إلى الفكرة الجوهرية ونبني كل شيء حولها.' },
        { title: 'الإتقان في كل تفصيل', desc: 'من الشعار إلى آخر تعليق، الجودة تُحَسّ ولا توصف.' },
        { title: 'شراكة لا مشاريع', desc: 'نعمل كفريق علامتك الداخلي، ملتزمون باللعب الطويل.' },
        { title: 'تُبنى لتبقى', desc: 'نصمّم هويات تظلّ صحيحة بعد سنوات، لا في يوم الإطلاق وحده.' },
      ],
      cta: 'اعمل معنا',
    },
    servicesPage: {
      kicker: 'قدراتنا',
      head: ['ماذا', 'نقدّم'],
      intro: 'ستة تخصصات مترابطة، ونظام علامة واحد. تعاون معنا في حاجة واحدة أو في الرحلة كاملة.',
      deliverablesLabel: 'ما تحصل عليه',
      items: [
        { deliverables: ['تدقيق العلامة والتموضع', 'التسمية والرسائل', 'دراسة الجمهور والسوق', 'نبرة الصوت'] },
        { deliverables: ['الشعار والكلمة-العلامة', 'نظام الهوية البصرية', 'الخطوط والألوان', 'دليل العلامة'] },
        { deliverables: ['تصميم وبناء المواقع', 'تجربة وواجهة المستخدم', 'أنظمة التواصل الاجتماعي', 'الحركة والتفاعل'] },
        { deliverables: ['أفكار الحملات', 'استراتيجية المحتوى', 'إدارة التواصل الاجتماعي', 'التواصل الداخلي'] },
        { deliverables: ['الطباعة والتغليف', 'التصوير والفيديو', 'تصميم الفعاليات والمكان', 'إدارة الإنتاج'] },
        { deliverables: ['شراكة تصميم مستمرة', 'القوالب وأدوات العمل', 'مكتبات الأصول', 'حوكمة العلامة'] },
      ],
      cta: 'لنتحدّث',
    },
    contact: {
      kicker: 'تواصل معنا',
      head: ['قل', 'مرحباً'],
      intro: 'حدّثنا عن علامتك وما تريد بناءه. نردّ خلال يومَي عمل.',
      form: {
        name: 'اسمك',
        email: 'البريد الإلكتروني',
        company: 'الشركة',
        budget: 'الميزانية',
        budgetOptions: ['غير محدّد بعد', 'أقل من $5k', '$5k – $15k', '$15k – $50k', '$50k+'],
        message: 'حدّثنا عن مشروعك',
        submit: 'إرسال الطلب',
        sending: 'جارٍ الإرسال…',
        success: 'شكراً — رسالتك في طريقها إلينا. سنتواصل خلال يومَي عمل.',
        required: 'يرجى تعبئة الحقول المطلوبة.',
      },
      detailsKicker: 'مباشرة',
      emailLabel: 'البريد',
      phoneLabel: 'الهاتف',
      locationLabel: 'الاستوديو',
      followLabel: 'تابعنا',
    },
  },
} as const;

export type Content = (typeof CONTENT)['en'];
